{{- include "ffc-helm-library.container-secret" (list . "ffc-grants-productivity-eligibility.container-secret") -}}
{{- define "ffc-grants-productivity-eligibility.container-secret" -}}
stringData:
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
  WORKSHEET_PROTECT_PASSWORD: {{ .Values.container.worksheetProtectPassword | quote }}
{{- end -}}
